# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Use the version pinned in requirements-dev.txt
    hooks:
    -   id: black
        # args: ["--line-length=88"] # Already configured in pyproject.toml

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2 # Use the version pinned in requirements-dev.txt
    hooks:
    -   id: isort
        name: isort (python)
        # args: ["--profile", "black"] # Already configured in pyproject.toml

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0 # Use the version pinned in requirements-dev.txt
    hooks:
    -   id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E501"] # Match pyproject.toml and ignore E501
        additional_dependencies: [
            'flake8-black==0.3.6',  # Match version in requirements-dev.txt
            'flake8-isort==6.1.1', # Match version in requirements-dev.txt
            # Add other flake8 plugins here if you use them
        ]

-   repo: local
    hooks:
    -   id: run-tests-before-push
        name: Run tests before push
        entry: make test
        language: system
        stages: [push] # This makes it a pre-push hook
        pass_filenames: false
